---
- name: Ensure requirements are in place
  ansible.builtin.dnf:
    name:
      - guestfs-tools
      - python3-libvirt
    state: present

- name: Get current vms list
  community.libvirt.virt:
    command: list_vms
  register: existing_vms
  changed_when: false

- name: Create vm if not exists
  when: "vm_name not in existing_vms.list_vms"
  block:
    - name: Copy base image to vm pool directory
      ansible.builtin.copy:
        dest: "{{ libvirt_pool_dir }}/{{ vm_name }}.qcow2"
        src: "{{ libvirt_image_dir }}/{{ base_image_name }}"
        owner: "{{ virt_user }}"
        group: "{{ virt_group }}"
        force: false
        remote_src: true
        mode: 0660
      register: copy_results

    - name: Configure the image using virt-customize
      ansible.builtin.command: |
        virt-customize -a {{ libvirt_pool_dir }}/{{ vm_name }}.qcow2 \
        --hostname "{{ hostname }}.{{ domain }}" \
        --root-password password:{{ root_pass }} \
        --ssh-inject 'root:file:{{ ssh_key }}' \
        --uninstall cloud-init --selinux-relabel
      when: copy_results is changed

    - name: Define vm using xml
      community.libvirt.virt:
        command: define
        xml: "{{ lookup('template', 'vm_template.xml.j2') }}"
