---
- name: Get vm ip address
  ansible.builtin.shell: |
    set -o pipefail && \
    virsh domifaddr {{ vm_name }} | \
    grep ipv4 | cut -c 47- | cut -d "/" -f 1
  changed_when: false
  register: virsh_output
  until: virsh_output['stdout'] != ""
  retries: 18
  delay: 5
  failed_when: virsh_output['stdout'] == ""

- name: Print vm ip address
  ansible.builtin.debug:
    msg: Current vm ip address is {{ virsh_output['stdout'] }}

- name: Verify vm ip address
  ansible.builtin.command: ping -c 5 {{ virsh_output['stdout'] }}
  changed_when: false

- name: Add vm to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    search_string: "{{ hostname }}"
    line: "{{ virsh_output['stdout'] }} {{ hostname }} {{ hostname }}.{{ domain }}"
    state: present
  register: hosts_file
  # notify: Update known_hosts file in vm host

- name: Update known_hosts file in vm host
  ansible.builtin.known_hosts:
    name: "{{ hostname }}"
    state: absent
  become: true
  become_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
  when: hosts_file.changed
