---
# defaults file for kvm_provision
# connection info
home_dir: /root
ssh_key_name: id_ed25519.pub
ssh_key: "{{ home_dir }}/.ssh/{{ ssh_key_name }}"

# vm spec variables
virt_user: qemu
virt_group: qemu
libvirt_pool_dir: /var/lib/libvirt/images
libvirt_image_dir: /var/lib/libvirt/images
base_image_name: rhel-8.7-x86_64-kvm.qcow2
vm_vcpus: 1
vm_ram_mb: 512
vm_net: default

# guest variables
root_pass: root
domain: example.com
vm_list:
  - { vm_name: vm-rhel8.7, hostname: host_rhel8 }
