---
# tasks file for host_configure
- name: Hosts to configure
  ansible.builtin.debug:
    var: inventory_hostname

- name: Configure guest tasks
  ansible.builtin.import_tasks: tasks_configure.yml

- name: Deploy packages tasks
  ansible.builtin.import_tasks: tasks_packages.yml
