---
- name: Configure user
  ansible.builtin.user:
    name: "{{ user_name }}"
    password: "{{ user_pass | password_hash('sha512', 65534 | random(seed=ansible_fqdn) | string) }}"
    groups: wheel
    state: present

- name: Configure ssh key for user
  ansible.posix.authorized_key:
    user: "{{ user_name }}"
    key: "{{ lookup('file', '{{ ssh_key }}') }}"
    state: present
  when: copy_ssh_key

- name: Get keymap
  ansible.builtin.shell: |
    set -o pipefail && \
    localectl | grep {{ keyboard_layout }}
  register: current_keymap
  failed_when: false
  changed_when: false

- name: Set keyborad layout
  ansible.builtin.command: localectl set-keymap {{ keyboard_layout }}
  register: localectl_output
  failed_when: localectl_output['rc'] != 0
  changed_when: localectl_output['rc'] == 0
  when: current_keymap['rc'] != 0

- name: Copy hosts file
  ansible.builtin.copy:
    src: "/etc/hosts"
    dest: "/etc/hosts"
    owner: root
    group: root
    mode: "0644"
    force: true
    backup: true
  when: copy_hosts_file

- name: Configure aliases for root and
  ansible.builtin.blockinfile:
    path: "{{ item }}"
    block: "{{ bashrc_aliases }}"
    marker: "## {mark} managed by ansible (aliases) ##"
    backup: true
  loop:
    - /root/.bashrc
    - /home/{{ user_name }}/.bashrc
