---
- name: Speed up dnf
  ansible.builtin.blockinfile:
    path: /etc/dnf/dnf.conf
    block: |
      max_parallel_downloads={{ max_parallel_downloads }}
      fastestMirror=true
  when: speedup_dnf

- name: Configure Redhat subscription on RHEL guests
  when:
    - ansible_facts['distribution'] == "RedHat"
    - install_packages or update_host
  block:
    - name: Get RHEL guest subscription status
      ansible.builtin.shell: |
        set -o pipefail && \
        subscription-manager status | \
        grep -i "overall status" | \
        cut -d ":" -f 2 | tr -d " "
      register: subscription_status
      failed_when: false
      changed_when: false

    - name: Register RHEL guest and attach subscription
      community.general.redhat_subscription:
        state: present
        username: "{{ redhat_username }}"
        password: "{{ redhat_password }}"
        pool_ids: "{{ subscription_pool }}"
      when: >
        ( subscription_status['stdout'] == "Unknown" )
        or
        ( subscription_status['stdout'] == "Invalid" )

- name: Install EPEL repo
  ansible.builtin.dnf:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm
    state: present
    disable_gpg_check: true

- name: Install packages
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present
  when: install_packages

- name: Update host
  ansible.builtin.dnf:
    name: '*'
    state: latest
    update_only: true
    update_cache: true
  when: update_host

- name: Remove obsolete packages
  ansible.builtin.dnf:
    autoremove: true
  when: install_packages or update_host

- name: Remove RHEL subscription
  community.general.redhat_subscription:
    state: absent
    username: "{{ redhat_username }}"
    password: "{{ redhat_password }}"
  when:
    - ansible_facts['distribution'] == "RedHat"
    - install_packages or update_host
    - clean_subscription
